#!/usr/bin/env bash
# Ping an IP address passed as an argument 5 times

import sys
import subprocess

def ping_ip(ip):
    """Ping an IP address passed as an argument 5 times"""
    ping = subprocess.run(['ping', '-c', '5', ip], stdout=subprocess.PIPE)
    if ping.returncode == 0:
        print(ip, 'is alive!')
    else:
        print(ip, 'is unreachable')
